/**
 * Search Orchestration Module
 * Implements deterministic multi-step legal research:
 * 1. Generate specific search queries based on case facts
 * 2. Execute searches via Google Gemini Grounding
 * 3. Inject retrieved snippets as context for final analysis
 */

import { GoogleGenAI } from '@google/genai';
import { safeLog, safeError, safeWarn } from './pii-redactor';

/**
 * Search query generated by the AI
 */
export interface SearchQuery {
  query: string;
  purpose: string;
  jurisdiction?: string;
}

/**
 * Search result snippet
 */
export interface SearchSnippet {
  query: string;
  title: string;
  snippet: string;
  url?: string;
  source?: string;
}

/**
 * Generate specific search queries based on the user's case
 * Uses AI to create targeted queries for legal research
 */
export async function generateSearchQueries(
  userInput: string,
  jurisdiction: string,
  apiKey: string
): Promise<SearchQuery[]> {
  try {
    const client = new GoogleGenAI({ apiKey });

    const prompt = `
Based on the following legal situation, generate exactly 3 specific search queries for legal research.

User's Situation: ${userInput}
Jurisdiction: ${jurisdiction}

Each query should be designed to find:
1. Relevant statutes or codes for this specific legal issue
2. Local court rules or procedures for this jurisdiction
3. Case law or legal precedents related to this matter

Return ONLY a JSON array in this exact format:
[
  {
    "query": "specific search query text",
    "purpose": "what this query is trying to find",
    "jurisdiction": "applicable jurisdiction if relevant"
  }
]

Make queries specific and actionable. For example:
- Instead of "eviction laws", use "California unlawful detainer notice requirements CCP 1161"
- Instead of "court rules", use "Los Angeles Superior Court ex parte application rules local rules"
`;

    const result = await client.models.generateContent({
      model: 'gemini-2.5-flash-preview-09-2025',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              query: { type: 'string' },
              purpose: { type: 'string' },
              jurisdiction: { type: 'string' },
            },
            required: ['query', 'purpose'],
          },
        },
      },
    });

    const queries: SearchQuery[] = JSON.parse(result.text || '[]');
    safeLog(`Generated ${queries.length} search queries for legal research`);

    return queries.slice(0, 3); // Ensure max 3 queries
  } catch (error) {
    safeError('Failed to generate search queries:', error);
    // Return fallback queries based on common patterns
    return generateFallbackQueries(userInput, jurisdiction);
  }
}

/**
 * Generate fallback queries if AI query generation fails
 */
function generateFallbackQueries(userInput: string, jurisdiction: string): SearchQuery[] {
  const queries: SearchQuery[] = [];
  const inputLower = userInput.toLowerCase();

  // Detect legal issue type
  if (inputLower.includes('eviction') || inputLower.includes('landlord') || inputLower.includes('tenant')) {
    queries.push({
      query: `${jurisdiction} unlawful detainer eviction notice requirements`,
      purpose: 'Find eviction notice requirements',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} tenant rights lockout self-help eviction`,
      purpose: 'Find tenant rights for lockouts',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} superior court housing ex parte application rules`,
      purpose: 'Find local court procedures',
      jurisdiction,
    });
  } else if (inputLower.includes('custody') || inputLower.includes('divorce') || inputLower.includes('family')) {
    queries.push({
      query: `${jurisdiction} child custody filing requirements forms`,
      purpose: 'Find custody filing requirements',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} family court local rules pro se`,
      purpose: 'Find family court procedures',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} child support guidelines calculation`,
      purpose: 'Find support guidelines',
      jurisdiction,
    });
  } else {
    // Generic queries
    queries.push({
      query: `${jurisdiction} pro se civil filing requirements`,
      purpose: 'Find general filing requirements',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} superior court local rules civil`,
      purpose: 'Find local court rules',
      jurisdiction,
    });
    queries.push({
      query: 'legal aid pro se resources self-represented',
      purpose: 'Find pro se resources',
    });
  }

  safeWarn('Using fallback search queries');
  return queries;
}

/**
 * Execute search using Google Gemini's grounding capabilities
 * This leverages Gemini's built-in search grounding
 */
export async function executeSearchWithGrounding(
  queries: SearchQuery[],
  apiKey: string
): Promise<SearchSnippet[]> {
  const allSnippets: SearchSnippet[] = [];

  for (const searchQuery of queries) {
    try {
      const client = new GoogleGenAI({ apiKey });

      // Use grounding to get search results
      const result = await client.models.generateContent({
        model: 'gemini-2.5-flash-preview-09-2025',
        contents: `Find relevant legal information about: ${searchQuery.query}`,
        config: {
          temperature: 0.1,
          maxOutputTokens: 500,
          // Enable Google Search grounding
          tools: [{ googleSearch: {} }],
        },
      });

      // Extract grounding metadata if available
      const groundingMetadata = result.candidates?.[0]?.groundingMetadata;
      const sources = groundingMetadata?.groundingChunks || [];
      const groundingSupports = groundingMetadata?.groundingSupports || [];

      // Extract snippets from grounding data
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const snippets: SearchSnippet[] = sources.map((source: any, index: number) => ({
        query: searchQuery.query,
        title: String(source.title || `Source ${index + 1}`),
        snippet: String(source.text || source.uri || 'No snippet available'),
        url: String(source.uri || ''),
        source: String(source.source || 'Google Search'),
      }));

      // If no grounding snippets, create a summary from the response
      if (snippets.length === 0 && result.text) {
        snippets.push({
          query: searchQuery.query,
          title: 'AI Research Summary',
          snippet: result.text.substring(0, 500),
          source: 'Gemini Analysis',
        });
      }

      allSnippets.push(...snippets.slice(0, 5)); // Limit to 5 snippets per query
    } catch (error) {
      safeError(`Search failed for query "${searchQuery.query}":`, error);
      // Add a placeholder snippet
      allSnippets.push({
        query: searchQuery.query,
        title: 'Search Unavailable',
        snippet: `Could not retrieve search results for: ${searchQuery.query}`,
        source: 'Error',
      });
    }
  }

  safeLog(`Retrieved ${allSnippets.length} search snippets`);
  return allSnippets;
}

/**
 * Format search snippets as context for the final prompt
 */
export function formatSearchContext(snippets: SearchSnippet[]): string {
  if (snippets.length === 0) {
    return 'No external search context available.';
  }

  let context = 'LEGAL RESEARCH CONTEXT (from verified sources):\n\n';

  snippets.forEach((snippet, index) => {
    context += `[Source ${index + 1}]: ${snippet.title}\n`;
    if (snippet.url) {
      context += `URL: ${snippet.url}\n`;
    }
    context += `Relevance: ${snippet.snippet}\n\n`;
  });

  context += '---\nINSTRUCTIONS: Use ONLY the above Context Data to support your legal analysis. ';
  context += 'Cite specific sources by number [Source X] when referencing this research.\n\n';

  return context;
}

/**
 * Complete orchestration workflow:
 * 1. Generate queries
 * 2. Execute searches
 * 3. Format context
 * Returns formatted context string for injection into final prompt
 */
export async function orchestrateLegalResearch(
  userInput: string,
  jurisdiction: string,
  apiKey: string
): Promise<string> {
  safeLog('Starting legal research orchestration...');

  try {
    // Step 1: Generate search queries
    const queries = await generateSearchQueries(userInput, jurisdiction, apiKey);
    safeLog(`Generated queries: ${queries.map(q => q.query).join('; ')}`);

    // Step 2: Execute searches with grounding
    const snippets = await executeSearchWithGrounding(queries, apiKey);

    // Step 3: Format context
    const context = formatSearchContext(snippets);

    safeLog('Legal research orchestration complete');
    return context;
  } catch (error) {
    safeError('Legal research orchestration failed:', error);
    return '\nRESEARCH NOTE: External legal research was unavailable. Proceeding with general legal knowledge.\n\n';
  }
}
