/**
 * Search Orchestration Module
 * Implements deterministic multi-step legal research:
 * 1. Generate specific search queries based on case facts
 * 2. Execute searches via GLM for legal analysis
 * 3. Inject retrieved snippets as context for final analysis
 */

import { safeLog, safeError, safeWarn } from './pii-redactor';

const GLM_API_URL = "https://api.z.ai/api/paas/v4/chat/completions";

/**
 * Search query generated by the AI
 */
export interface SearchQuery {
  query: string;
  purpose: string;
  jurisdiction?: string;
}

/**
 * Search result snippet
 */
export interface SearchSnippet {
  query: string;
  title: string;
  snippet: string;
  url?: string;
  source?: string;
}

/**
 * Generate specific search queries based on the user's case
 * Uses AI to create targeted queries for legal research
 */
export async function generateSearchQueries(
  userInput: string,
  jurisdiction: string,
  apiKey: string
): Promise<SearchQuery[]> {
  try {
    const prompt = `
Based on the following legal situation, generate exactly 3 specific search queries for legal research.

User's Situation: ${userInput}
Jurisdiction: ${jurisdiction}

Each query should be designed to find:
1. Relevant statutes or codes for this specific legal issue
2. County-level Local Rules of Court and specific procedural requirements for this jurisdiction. PRIORITIZE THE "MONDAY MORNING RULE": find procedural technicalities (filing deadlines, ex parte notice times, mandatory forms) that could cause a case to be dismissed.
3. Case law or legal precedents related to this matter

Return ONLY a JSON array in this exact format:
[
  {
    "query": "specific search query text",
    "purpose": "what this query is trying to find",
    "jurisdiction": "applicable jurisdiction if relevant"
  }
]
`;

    const systemPrompt = 'You are a legal research specialist. Return ONLY valid JSON, no markdown or additional text.';

    const response = await fetch(GLM_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: "glm-4.7-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: prompt }
        ],
        temperature: 0.1,
        max_tokens: 1024
      })
    });

    if (!response.ok) {
      throw new Error(`GLM API error: ${response.status}`);
    }

    const data = await response.json();
    const responseText = data.choices?.[0]?.message?.content || '[]';
    
    // Try to extract JSON from response
    const jsonMatch = responseText.match(/\[[\s\S]*\]/);
    const jsonString = jsonMatch ? jsonMatch[0] : '[]';
    
    const queries: SearchQuery[] = JSON.parse(jsonString);
    safeLog(`Generated ${queries.length} search queries for legal research`);

    return queries.slice(0, 3); // Ensure max 3 queries
  } catch (error) {
    safeError('Failed to generate search queries:', error);
    // Return fallback queries based on common patterns
    return generateFallbackQueries(userInput, jurisdiction);
  }
}

/**
 * Generate fallback queries if AI query generation fails
 */
function generateFallbackQueries(userInput: string, jurisdiction: string): SearchQuery[] {
  const queries: SearchQuery[] = [];
  const inputLower = userInput.toLowerCase();

  // Detect legal issue type
  if (inputLower.includes('eviction') || inputLower.includes('landlord') || inputLower.includes('tenant')) {
    queries.push({
      query: `${jurisdiction} unlawful detainer eviction notice requirements`,
      purpose: 'Find eviction notice requirements',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} tenant rights lockout self-help eviction`,
      purpose: 'Find tenant rights for lockouts',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} superior court housing ex parte application rules`,
      purpose: 'Find local court procedures',
      jurisdiction,
    });
  } else if (inputLower.includes('custody') || inputLower.includes('divorce') || inputLower.includes('family')) {
    queries.push({
      query: `${jurisdiction} child custody filing requirements forms`,
      purpose: 'Find custody filing requirements',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} family court local rules pro se`,
      purpose: 'Find family court procedures',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} child support guidelines calculation`,
      purpose: 'Find support guidelines',
      jurisdiction,
    });
  } else {
    // Generic queries
    queries.push({
      query: `${jurisdiction} pro se civil filing requirements`,
      purpose: 'Find general filing requirements',
      jurisdiction,
    });
    queries.push({
      query: `${jurisdiction} superior court local rules civil`,
      purpose: 'Find local court rules',
      jurisdiction,
    });
    queries.push({
      query: 'legal aid pro se resources self-represented',
      purpose: 'Find pro se resources',
    });
  }

  safeWarn('Using fallback search queries');
  return queries;
}

/**
 * Execute search using GLM for legal research synthesis
 * Note: GLM doesn't have built-in search grounding, so we use it for legal analysis
 */
export async function executeSearchWithGrounding(
  queries: SearchQuery[],
  apiKey: string
): Promise<SearchSnippet[]> {
  const allSnippets: SearchSnippet[] = [];

  for (const searchQuery of queries) {
    try {
      const prompt = `Provide a concise summary of relevant legal information about: ${searchQuery.query}

Include:
- Key legal principles or rules
- Relevant statutes or case names if applicable
- Practical implications

Keep your response under 200 words.`;

      const systemPrompt = 'You are a legal research assistant. Provide accurate, concise legal information.';

      const response = await fetch(GLM_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: "glm-4.7-flash",
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: prompt }
          ],
          temperature: 0.1,
          max_tokens: 500
        })
      });

      if (!response.ok) {
        throw new Error(`GLM API error: ${response.status}`);
      }

      const data = await response.json();
      const responseText = data.choices?.[0]?.message?.content || 'No information available';

      allSnippets.push({
        query: searchQuery.query,
        title: 'Legal Research Summary',
        snippet: responseText.substring(0, 500),
        source: 'GLM Analysis',
      });
    } catch (error) {
      safeError(`Search failed for query "${searchQuery.query}":`, error);
      // Add a placeholder snippet
      allSnippets.push({
        query: searchQuery.query,
        title: 'Search Unavailable',
        snippet: `Could not retrieve search results for: ${searchQuery.query}`,
        source: 'Error',
      });
    }
  }

  safeLog(`Retrieved ${allSnippets.length} search snippets`);
  return allSnippets;
}

/**
 * Format search snippets as context for the final prompt
 */
export function formatSearchContext(snippets: SearchSnippet[]): string {
  if (snippets.length === 0) {
    return 'No external search context available.';
  }

  let context = 'LEGAL RESEARCH CONTEXT (from AI analysis):\n\n';

  snippets.forEach((snippet, index) => {
    context += `[Source ${index + 1}]: ${snippet.title}\n`;
    context += `Query: ${snippet.query}\n`;
    context += `Analysis: ${snippet.snippet}\n\n`;
  });

  context += '---\nINSTRUCTIONS: Use ONLY the above Context Data to support your legal analysis. ';
  context += 'Note: This is AI-generated legal information, not verified legal advice.\n\n';

  return context;
}

/**
 * Complete orchestration workflow:
 * 1. Generate queries
 * 2. Execute searches
 * 3. Format context
 * Returns formatted context string for injection into final prompt
 */
export async function orchestrateLegalResearch(
  userInput: string,
  jurisdiction: string,
  apiKey: string
): Promise<string> {
  safeLog('Starting legal research orchestration...');

  try {
    // Step 1: Generate search queries
    const queries = await generateSearchQueries(userInput, jurisdiction, apiKey);
    safeLog(`Generated queries: ${queries.map(q => q.query).join('; ')}`);

    // Step 2: Execute searches with grounding
    const snippets = await executeSearchWithGrounding(queries, apiKey);

    // Step 3: Format context
    const context = formatSearchContext(snippets);

    safeLog('Legal research orchestration complete');
    return context;
  } catch (error) {
    safeError('Legal research orchestration failed:', error);
    return '\nRESEARCH NOTE: External legal research was unavailable. Proceeding with general legal knowledge.\n\n';
  }
}
