from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from google import genai
from google.genai import types
import os
from typing import Any, Callable
from pydantic import BaseModel
from .models import (
    LegalRequest,
    WebChunk,
    GroundingChunk,
    GroundingMetadata,
    Part,
    Content,
    GeminiCandidate,
    Source,
    LegalResult,
    HealthResponse,
)

app = FastAPI()

@app.middleware("http")
async def log_requests(request: Any, call_next: Callable[[Any], Any]) -> Any:
    print(f"Incoming request: {request.method} {request.url.path}")
    response = await call_next(request)
    print(f"Response status: {response.status_code}")
    return response

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
@app.get("/health")
async def health_check() -> HealthResponse:
    return HealthResponse(status="ok", message="LawSage API is running")

@app.post("/api/generate", response_model=LegalResult)
async def generate_legal_help(request: LegalRequest, x_gemini_api_key: str | None = Header(None)) -> LegalResult:
    if not x_gemini_api_key:
        raise HTTPException(status_code=401, detail="GEMINI_API_KEY is missing")
    
    try:
        client = genai.Client(api_key=x_gemini_api_key, http_options={'api_version': 'v1alpha'})
        
        # Enable Grounding with Google Search
        search_tool = types.Tool(
            google_search=types.GoogleSearch()
        )
        
        prompt = f"""
        User Situation: {request.user_input}
        Jurisdiction: {request.jurisdiction}
        
        Act as a Universal Public Defender. 
        1. Search for current statutes and local court procedures relevant to this situation.
        2. Provide a breakdown of the situation in plain English.
        3. Generate a procedural roadmap (step-by-step instructions).
        
        ---
        
        4. Generate the text for necessary legal filings that are court-admissible in the specified jurisdiction.
        
        Format the response such that the strategy and roadmap come BEFORE the '---' delimiter, and the actual legal filings come AFTER the '---' delimiter.
        
        Explicitly state that you are an AI helping the user represent themselves (Pro Se) and that this is legal information, not legal advice.
        """
        
        MODEL_ID = "gemini-2.5-flash"
        
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=prompt,
            config=types.GenerateContentConfig(
                tools=[search_tool]
            )
        )
        
        text_output = ""
        sources = []
        
        if response.candidates and len(response.candidates) > 0:
            raw_candidate = response.candidates[0]
            print(f"Raw response candidate: {raw_candidate}")
            
            try:
                # Use Pydantic to validate the raw candidate object
                candidate = GeminiCandidate.model_validate(raw_candidate)
                
                # Check for safety or other non-success finish reasons
                if candidate.finish_reason in ["SAFETY", "RECITATION", "OTHER"]:
                    return LegalResult(
                        text=f"The AI was unable to complete the request due to safety filters or other constraints (Reason: {candidate.finish_reason}). Please try rephrasing your request to be more specific or focused on legal information.\n\n---\n\nNo filings generated.",
                        sources=[]
                    )

                # Join all text parts if there are multiple
                if candidate.content and candidate.content.parts:
                    text_output = "\n".join([p.text for p in candidate.content.parts if p.text])
                else:
                    text_output = "No content was generated by the model.\n\n---\n\nNo filings generated."

                # Reliability Delimiter: Ensure '---' exists for frontend split logic
                if '---' not in text_output:
                    text_output += "\n\n---\n\nNo filings generated. Please try a more specific request."
                
                if candidate.grounding_metadata and candidate.grounding_metadata.grounding_chunks:
                    for chunk in candidate.grounding_metadata.grounding_chunks:
                        if chunk.web:
                            sources.append(Source(title=chunk.web.title, uri=chunk.web.uri))
            except Exception as e:
                print(f"Error validating candidate: {e}")
                # Fallback to manual parsing if Pydantic fails
                text_output = f"Error processing model response: {str(e)}\n\n---\n\nNo filings generated."
        else:
            text_output = "I'm sorry, I couldn't generate a response for that situation. The model returned no candidates.\n\n---\n\nNo filings generated."

        return LegalResult(
            text=text_output,
            sources=sources
        )
    except Exception as e:
        print(f"ERROR in generate_legal_help: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
